### ISSUE TITLE
Inherited `default` is not validated

### ISSUE THREAD

**Issue by maximlt** [holoviz/param#714]
The value of a Parameter *attribute* - like `default`, `doc`, etc. - is inherited in a hierarchy of Parameterized classes. In practice, the inheritance only applies when the default attribute value is `None`.

In the example below, `B` is a subclass of `A` and the user intent seems to be to override the definitions of `p1` and `p2`, from `String` and `String` to `Action` to `Number`, respectively. The result of that operation is that:
- Because the default value of the `default` attribute of `Action` is `None`, `B.p1.param.default` will inherit from `A.p1.param.default` which is `'1'`. The value of `p1` is then set based on that new `default`, leading to `b.p1 == '1'`. This is an invalid value for a `Number`.
- Because the default value of the `default` attribute of `Action` is not `None` but `0.0`, it is used directly to set `B.p1.param.default`, leading to `b.p1 == 0.0`.

```python
import param

class A(param.Parameterized):
    p1 = param.String(default='1')
    p2 = param.String(default='1')

class B(A):
    p1 = param.Action()
    p2 = param.Number()

b = B()

assert b.p1 == '1'  # passes
assert b.p2 == 0.0  # passes
```

The focus of this issue is on the `default` attribute as it can be used to set the actual Parameter value, if the user does not provide a default when instantiating the class. But this issue is more general, the Parameters of a subclass can inherit other invalid attributes without any error/warning.

This discussion is linked to the proposal of enforcing an "is-a" relationship (https://github.com/holoviz/param/issues/97#issuecomment-783734974) between Parameters in a class hierarchy.

A pragmatic approach to this issue might be to run the Parameter validation code (`Parameter._validate`) after the whole inheritance procedure is executed, and emit a warning if that fails. As to avoid the issue above with `p1`, the author of `B` should define a default value for the overriding `p1`.

**Comment by jbednar** [comment]
I agree that enforcing `is-a` would address this, but it also seems appropriate to run `_validate` on whatever the result of inheritance is.

**Comment by jbednar** [comment]
Note that the behavior of main is now more reasonable (no longer type dependent), though still not validating as it should:

<img width="312" alt="image" src="https://github.com/holoviz/param/assets/1695496/ec9bf00d-e004-450b-b511-f021ed02c82a">

**Comment by jbednar** [comment]
Fixed by #812.

**Comment by maximlt** [comment]
@jbednar this is not completely fixed. #812 only added validation of _default_ when a Parameter is not a subclass of it parent Parameter. So there's no validation in that kind of more common case:

```python
import param

class A(param.Parameterized):
    x = param.Number(5, bounds=(3, 10))

class B(A):
    x = param.Number(0)

b = B()
b.x
# 0
```
